### ISSUE TITLE
UAC Bypass

### ISSUE THREAD

**Issue by aabilityuk** [trowx/AdminToAuthoritySytem#1]
Hi, first of all thank you very much for code sharing!!! slui.exe works perfect, but i can't find out how to bypass uac on my own xxx.exe

Could you please help to make it work, and give me a tip what am i doing wrong? I changed the 1023 string of code like this:

	`ShellExecuteW(NULL, L"runas", L"C:\\Windows\\System32\\xxx.exe", NULL, NULL, SW_SHOWNORMAL);`

but it doesn't bypass UAC :(

Thank you

**Comment by trowx** [comment]
1- edit https://github.com/trowx/AdminToAuthoritySytem/blob/2bb8e59922e31a4764a73613d5a4188d1053c3c5/uac/uac/dllmain.cpp#L15

2- compile dll

3- use HxD editor and copy bytes 

4- paste https://github.com/trowx/AdminToAuthoritySytem/blob/2bb8e59922e31a4764a73613d5a4188d1053c3c5/AdminToAuthoritySytem/AdminToAuthoritySytem/AdminToAuthoritySytem.cpp#L16
